### PR TITLE
fix bug where old approvals are counted toward requirement

### LINKED ISSUE #32: BUG: Approvals count is wrong when reviewer approves and changes mind later
This is primarily an edge case:

## To Reproduce:
- By default the minimum approvals is 1.
- Approve a PR.
- Then change the review status to Comment, which removes your approval status.

## Actual:
Mergeable is true.

## Expected:
Mergeable should be false since the number of approval count is actually zero.

### PR DESCRIPTION
**Pull request by shine2lay**
closes #32 

NOTE: this PR adds a new package `lodash`, npm install will be required after merging

### CODE REVIEW

File: lib/approvals.js [hunk 1]
```diff
@@ -23,3 +26,11 @@ module.exports = async (pr, context, settings) => {
 
   return processor.processFilters('Approval', approvedReviewers, approvalSettings)
 }
+
+const filterOutOldReviews = (reviews) => {
+  const ordered = _.orderBy(reviews, ['submitted_at'], ['desc'])
+  console.log('ordered', ordered)
```
Comment (jusx) [inline lib/approvals.js]: should remove this.
