### PR TITLE
fix #98 + test to mimic the same scenario

### LINKED ISSUE #98: Title: must_include: regex fails with "TypeError: Cannot read property 'trim' of null"
When trying to validate pull request titles, mergeable fails with the following:

image

I've tried using the example from the readme:

```
title:
  must_include:
    regex: `^\\(feat\\)|^\\(doc\\)|^\\(fix\\)`
      message: `Title must have prefixes for the following: (feat), (doc), (fix)`
```

and the following:

```
  must_include:
    regex: `#\d{7,}'
```

### PR DESCRIPTION
**Pull request by shine2lay**
closes #98 
Please see comments for more information about the bug https://github.com/jusx/mergeable/issues/98#issuecomment-426302899

### CODE REVIEW

File: lib/processor.js [hunk 1]
```diff
@@ -5,6 +5,11 @@
  * @returns object { mergeable: bool, description: string | [string]}
  */
 const processFilters = (validatorContext, input, filters) => {
+  // if input is null or undefined, turn it into empty string
+  if (!input) {
```
Comment (jusx) [inline lib/processor.js]: To be on the safe side I propose using a double bang here. i.e. `(!!input)`

Comment (shine2lay) [reply lib/processor.js]: standard said `no double negation`, would you prefer i don't fix this ? or fix standard?
