### PR TITLE
show `action_requested` if error occurs

### LINKED ISSUE #72: YML Exception Should Bubble Up
### Context
When the mergeable YML does not have expected indentation or the format is wrong `js-yaml` throws an exception and mergeable does not stop running.

### Proposal
- Mergeable should catch these exceptions and notify.
- **Potential Notifications:**
   - Set a status on PR with bad YML configuration found. Ideally the details should link to a mergeable
   - Send a checks with explanation about YML problem.
   - Comment on the PR or issue when the problem is found.

### PR DESCRIPTION
**Pull request by shine2lay**
closes #72 

Screen shot of the error message
image

### CODE REVIEW

File: lib/handler.js [hunk 1]
```diff
@@ -73,52 +73,61 @@ class Handler {
...
-      if (failures.length === 0) {
-        status = 'success'
-        description = 'Okay to merge.'
-      } else {
-        status = 'failure'
-        description = `## Mergeable has found the following failed checks`
-        for (let validated of failures) {
-          description += `\n - ${validated.description}`
+    try {
+      var config = await Configuration.instanceWithContext(context)
```
Comment (jusx) [inline lib/handler.js]: IMO the try catch should be around this statement where it is an actual error from loading / processing the configuration.

File: lib/handler.js [hunk 2]
```diff
@@ -73,52 +73,61 @@ class Handler {
...
+          'completed',
+          status,
+          {
+            title: `Result: ${status}`,
+            summary: description})
+
+        console.info({state: status, description: description})
+      }).catch(error => {
+        // (jusx) This should never ever happen. Log it.
+        console.error(error)
```
Comment (jusx) [inline lib/handler.js]: There should probably be a `checks.update` here for general errors. Though likely no action required because it isn't really configuration related. This will likely be like a "HTTP 500".

File: lib/handler.js (hunk 1 above)
Comment (shine2lay) [reply lib/handler.js]: i thought we want to do a general try and catch for all unknown errors

File: lib/handler.js (hunk 2 above)
Comment (shine2lay) [reply lib/handler.js]: removed that `catch` the try and catch block should catch this error as well

File: lib/handler.js [hunk 3]
```diff
@@ -73,52 +73,58 @@ class Handler {
...
         'Mergeable',
         'completed',
-        status,
+        'action_required',
         {
-          title: `Result: ${status}`,
-          summary: description})
-
-      console.info({state: status, description: description})
-    }).catch(error => {
```
Comment (jusx) [inline lib/handler.js]: This catches `promise` rejections. Removing this will cause unknown errors to go unlogged. I really don't think it should be removed. Normal try catches will do anything here as this is async.

Furthermore at this point it's errors thrown by validators are not due to bad configuration and are typically errors caused by system bugs snda hence the message should tell the user that a "system error has occurred"  -- it's not something they can do on their end. I also really would like these errors to be logged.

File: lib/handler.js (hunk 1 above)
Comment (jusx) [reply lib/handler.js]: The original catch was on `Promise.all` and would have caught any promise rejections in this entire function.

The only other place where an error could occur is during the loading of Configuration. A try catch around that with the very specific message telling the user to fix their configuration will suffice. It is actionable. The promise rejections from the validators are unlikely to be actionable. It deserves it's own message and an error log since it's most likely to be a bug.

File: lib/handler.js [hunk 4]
```diff
@@ -115,9 +126,16 @@ class Handler {
           summary: description})
 
       console.info({state: status, description: description})
-    }).catch(error => {
-      // (jusx) This should never ever happen. Log it.
-      console.error(error)
+    }).catch(err => {
+      checks.update(
```
Comment (jusx) [inline lib/handler.js]: We should log the error as well so that we are aware of it and can fix the bug.

Comment (shine2lay) [reply lib/handler.js]: done
